./bin/i18n-build: require --all for building all packages.
Developers usually work on a specific package and want to rebuild this
package, not all translations.
Running bin/i18n-build without arguments used to build all packages
and was hard to abort because of the subprocesses, leaving the
developer with many unwanted changes when executing accidentally.
Therefore it is now required to explicitly use --all or a specific
package name.

diff --git a/bin/i18n-build b/bin/i18n-build
--- a/bin/i18n-build
+++ b/bin/i18n-build
@@ -2,9 +2,10 @@
 #
 # USAGE:
 # bin/i18n-build [pkgname]
+# bin/i18n-build --all
 #
 # If a [pkgname] is supplied, only translation files for that package will be
-# built. Otherwise they will be built for all packages.
+# built. Otherwise use --all for all packages.
 #
 # This script builds translation files for opengever.core.
 #
@@ -19,6 +20,13 @@ pkg_dir=`bin/package-directory`
 core_dir=`dirname $pkg_dir`
 locales_dirs=`find $pkg_dir -name 'locales'`
 
+if [ $# -eq 0 ] || [ "$1" == "--help" ]; then
+    echo "ERROR: Either provide a package name or use --all for all packages."
+    echo "Example: ./bin/i18n-build --all"
+    echo "Example: ./bin/i18n-build opengever.task"
+    exit 1
+fi
+
 for locale_dir in $locales_dirs
 do
     # Strip /locales
@@ -30,7 +38,7 @@ do
     pkgname=${pkg_relpath//\//.}            # opengever.dossier
 
     # checks if a specific package is selected
-    if [ $# -eq 1 ] && [ "$1" != "$pkgname" ]; then
+    if [ "$1" != "--all" ] && [ "$1" != "$pkgname" ]; then
       continue
     fi
 
